# config/dataset/re10k.yaml
# defaults:
#   - view_sampler: bounded

# name: re10k
# roots: [datasets/re10k]
# make_baseline_1: true
# augment: true

# image_shape: [256, 256] # [180, 320]
# background_color: [0.0, 0.0, 0.0]
# cameras_are_circular: false

# baseline_epsilon: 1e-3
# max_fov: 100.0

defaults:
  - view_sampler: bounded

name: re10k
roots: ["/home/gengqt/latentsplat-live/latentsplat-v0.1-a100/re10k"]
skip_missing: false
strict: false
allow_empty: false
make_baseline_1: true
augment: true
image_shape: [256,256]         
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false
baseline_epsilon: 1.0e-3
max_fov: 100.0

# 3060 提速
trainer:
  precision: 16-mixed
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 5

data_loader:
  train:
    num_workers: 8
    pin_memory: true
